### ISSUE TITLE
error happens for sun-photon compile

### ISSUE THREAD

**Issue by zem007** [tronprotocol/sun-photon#3]
_node version: v12.13.1
npm version: 6.12.1_

I try to compile and migrate the **_DonateNow_** contracts exactly the same with the demo codes, but error happens when I am using _**sun-photon compile**_ :

$ sun-photon compile
Error: Error parsing D:/DappRepositories/sunnet-donate/contracts/common/Address.sol: Cannot find module 'C:\Users\Admin\.sunphoton\solc\soljson_v0.4.25.js'
Require stack:
- C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\components\TronSolc.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\lib\commands\version.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\lib\commands\index.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\index.js
- C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\sun-photon.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getWrapper (C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\components\TronSolc.js:1:1804)
    at Object.parseImports (C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\components\Compile\parser.js:1:2465)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\components\Compile\profiler.js:1:5144
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\build\components\Resolver\index.js:1:1727
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\node_modules\async\internal\onlyOnce.js:12:16
    at next (C:\Users\Admin\AppData\Roaming\npm\node_modules\sun-photon\node_modules\async\whilst.js:68:18)

Maybe I should uninstall all the npm modules and install all the necessary again, but anyone knows how to fix it?

**Comment by llwslc** [comment]
try download the soljson_v0.4.25.js from [solc](https://github.com/TRON-US/tron-solc-bin/tree/master/bin)

**Comment by zem007** [comment]
> try download the soljson_v0.4.25.js from [solc](https://github.com/TRON-US/tron-solc-bin/tree/master/bin)

fixed. thanks
